name: "Caller Workflow"

on:
  workflow_dispatch:
    inputs:
      actor:
        description: "The person who will receive the greeting"
        required: true
        type: string

jobs:
  call-reusable:
    uses: tamtanns/Playground/.github/workflows/reusable_workflow.yml@main
    with:
      actor: ${{ inputs.actor }}
